manifest = "fc4771db286e2049cdf0c92b06b5c1d81b29d894329fde0fb0b49a19c8670b4a"

[[dependency]]
package = "github.com/buckaroo-pm/boost-chrono"
target = "//:chrono"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-io"
target = "//:io"

[[dependency]]
package = "github.com/buckaroo-pm/boost-system"
target = "//:system"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw-exception"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "branch=master" ]
revision = "f9d6a7b63ef2902777b6078fdebc54e7a57aac03"

[lock."github.com/buckaroo-pm/boost-chrono"]
versions = [ "branch=master" ]
revision = "0d9de7ea384e6e70d788667bb78c94f2cfe8949a"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "4392ed19b232ed2dde7623843d7e30ef669d860e"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "branch=master" ]
revision = "84411b155dae6f08ea749bdeb1e71aecd0718d52"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "branch=master" ]
revision = "e8b834a93f7ba935aa63a3d6690804f3bd2b0963"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "branch=master" ]
revision = "c43bde6de716aeaa1958f523576599c384791da2"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "branch=master" ]
revision = "5badcf5b232a15e89d0701bef687ffbe70398696"

[lock."github.com/buckaroo-pm/boost-io"]
versions = [ "branch=master" ]
revision = "70c28ebaa83b1fd6907db8f542d7be8abc6835b4"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "branch=master" ]
revision = "c50bef004827b93d7f60e3c53b8c9c3b54fa0084"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "branch=master" ]
revision = "a1873af9c1d31fb8ec2a87482b6bb9729439b4ac"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "branch=master" ]
revision = "c52d78d2ae7cc323da79c23375b7efe8c2c8078d"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "branch=master" ]
revision = "4d01d0f9c0ae3ae3cd20e3cbfddbc9909ce8e064"

[lock."github.com/buckaroo-pm/boost-ratio"]
versions = [ "branch=master" ]
revision = "dabc418e4bb7a180d5d17c84fb4f0bd61a9ee024"

[lock."github.com/buckaroo-pm/boost-rational"]
versions = [ "branch=master" ]
revision = "7a75e06a78e0481cb636412a62764f628ec8e56b"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "branch=master" ]
revision = "fdc2df7f811436674a1c55c766b8830a8cd02e96"

[lock."github.com/buckaroo-pm/boost-system"]
versions = [ "branch=master" ]
revision = "16cad275bcf88549063d1f01a4fbf483ea36e7cd"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "branch=master" ]
revision = "3951e0ca1d6b909bbc815858acbe2449c4a53eed"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "branch=master" ]
revision = "4d0a507c0d1a1011c5a98d57acc9f6b755141e4f"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "branch=master" ]
revision = "e8cb7bc76c55f02a24f824fecf5cdf0629dc3aa4"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "branch=master" ]
revision = "f04cf922658a7e03776631a96c3ad346ad179d5f"

[lock."github.com/buckaroo-pm/boost-winapi"]
versions = [ "branch=master" ]
revision = "92c47b2e1db8a7c023d394e979f81438b410fd18"
