manifest = "fc4771db286e2049cdf0c92b06b5c1d81b29d894329fde0fb0b49a19c8670b4a"

[[dependency]]
package = "github.com/buckaroo-pm/boost-chrono"
target = "//:chrono"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-io"
target = "//:io"

[[dependency]]
package = "github.com/buckaroo-pm/boost-system"
target = "//:system"

[[dependency]]
package = "github.com/buckaroo-pm/boost-throw_exception"
target = "//:throw-exception"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "branch=master" ]
revision = "fc4d65435c49b5b4fbbf0d4867ee8f69bfd42ef1"

[lock."github.com/buckaroo-pm/boost-chrono"]
versions = [ "branch=master" ]
revision = "d9135ae23f09a15931dbd15a99324dfe44954aba"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "60c77dd14f5bac2b9e6c59f308b7ad20d31f70ab"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "branch=master" ]
revision = "82480080750b32b3ef2e3f12157b5c556ae35c0d"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "branch=master" ]
revision = "ec2d46a5e413ca9f1c97b2628732bc114e83e3f8"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "branch=master" ]
revision = "1795a6e9756f4d9ac60d43e2b9b07ec7ddfdbfb7"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "branch=master" ]
revision = "5badcf5b232a15e89d0701bef687ffbe70398696"

[lock."github.com/buckaroo-pm/boost-io"]
versions = [ "branch=master" ]
revision = "70c28ebaa83b1fd6907db8f542d7be8abc6835b4"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "branch=master" ]
revision = "3f0711cabd643ed902ff3ae3d6746ba2f7256e4e"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "branch=master" ]
revision = "6493fcda0f5cd2ee595346ca48ff495db9fa74d5"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "branch=master" ]
revision = "73def0812b7235e0312079c729342787819bf1d5"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "branch=master" ]
revision = "a70772bbd315eb597c3f1e359af742dde46a6f37"

[lock."github.com/buckaroo-pm/boost-ratio"]
versions = [ "branch=master" ]
revision = "1b80056654a5ca6384e54d925cfdd58feee28f63"

[lock."github.com/buckaroo-pm/boost-rational"]
versions = [ "branch=master" ]
revision = "7a75e06a78e0481cb636412a62764f628ec8e56b"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "branch=master" ]
revision = "8256c9846a133573ff959e0a7dc0cadb8fba5192"

[lock."github.com/buckaroo-pm/boost-system"]
versions = [ "branch=master" ]
revision = "d98315738ee47380f52e43d790d1c42cf549b175"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "branch=master" ]
revision = "788503e2365554d1860c6d2043999e3430d1f7a5"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "branch=master" ]
revision = "b8e0fcc49cede65c3b4ef18ed5aa797225578467"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "branch=master" ]
revision = "e8cb7bc76c55f02a24f824fecf5cdf0629dc3aa4"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "branch=master" ]
revision = "57aa216434800315c9cd2664169e444e3070a677"

[lock."github.com/buckaroo-pm/boost-winapi"]
versions = [ "branch=master" ]
revision = "92c47b2e1db8a7c023d394e979f81438b410fd18"
